project_id = "hspfyakugditkxrvngrc"

[functions.generate-event-image]
verify_jwt = false

[functions.event-reminders]
verify_jwt = false

[functions.get-vapid-key]
verify_jwt = false

[functions.send-push-notification]
verify_jwt = false

[functions.user-reengagement]
verify_jwt = false
